### ISSUE TITLE
关于sparse sampling module

### ISSUE THREAD

**Issue by lebron-2016** [ChaoXiao12/Moving-object-detection-in-satellite-videos-HiEUM#2]
尊敬的作者：

您好！

我最近学习了您的工作，受益匪浅。

关于sparse sampling module我有一点困惑是：您在得到每一帧的激活区域时，是通过相邻帧两两之间进行计算并阈值过滤的吗？

期待您的回复，

感谢您的帮助！！

**Comment by ChaoXiao12** [comment]
您好，关于稀疏采样模块是这样设计的：首先通过时域中值滤波得到背景图像，然后进行背景差分得到残差图，对每一帧图像计算均值和方差通过自适应阈值分割获取得到每一帧的激活区域。

**Comment by lebron-2016** [comment]
> 您好，关于稀疏采样模块是这样设计的：首先通过时域中值滤波得到背景图像，然后进行背景差分得到残差图，对每一帧图像计算均值和方差通过自适应阈值分割获取得到每一帧的激活区域。

感谢您的解答。

还有一点困惑是，通过这种方式得到的激活“点”可能不能够完整的表示一些目标（存在误差），那么直接将它们代替原始图像送入模型进行预测是否会造成一些目标的位置、尺寸预测不准呢？以及这种方式会产生较多的噪点（离群点），这是否会造成虚警率变高呢？

感谢。

**Comment by ChaoXiao12** [comment]
这样采样的目的主要在于减少需要计算量。随着采样阈值的提升，采样区域不可避免的会导致目标区域的丢失，造成检测性能的下降，但是采样点数也会大幅下降，使得运行效率获得极大提升（详情见论文内容）。采用这样简单的采样方式也是为了算法整体效率，不能完全消除杂波点的影响，但是后续网络会去除部分杂波点，得到最终结果。

**Comment by lebron-2016** [comment]
> 。采用这样简单的采样方式也是为了算法整体效率，不能完全消除杂波点的影响，但是后续网络会去除部分杂波点，得到最终结

明白了，感谢您的解答
