### ISSUE TITLE
测试流程

### ISSUE THREAD

**Issue by lebron-2016** [ChaoXiao12/Moving-object-detection-in-satellite-videos-HiEUM#3]
您好，

还想问下您的模型在测试时的流程是怎样的？是把数据集以20帧为单位切成几段，然后分别送入模型吗？

期待您的回复，

感谢！！

**Comment by ChaoXiao12** [comment]
您好，感谢关注我们的工作。我们是将一段序列以20帧为一小段输入到网络中进行处理。相应的在代码test代码里有体现。
